[package]
name = "snui"
version = "0.1.0"
authors = ["Bryan Ndjeutcha <ndjeutcha@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.5.2"
font-kit = "0.5.0"
wayland-commons = "0.28.5"
wayland-client = "0.28.5"
euclid = "0.20.0"
raqote = "0.7.14"
smithay-client-toolkit = "0.14.0"
wayland-protocols = { version="0.28.5", features=["unstable_protocols", "client"] }
image = "0.23.14"
