[package]
name = "snui"
version = "0.1.0"
authors = ["Bryan Ndjeutcha <ndjeutcha@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fontdue = "0.6.2"
tiny-skia = "0.6.1"
fontconfig = "0.2.1"
wayland-client = "0.28.5"
wayland-commons = "0.28.5"
smithay-client-toolkit = "0.14.0"
image = { version="0.23.14", features=["jpeg", "png"] }
wayland-protocols = { version="0.28.5", features=["unstable_protocols", "client"] }
